name: Build and publish to gh-pages
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          env
          yarn
          yarn build
          rm dist/.htaccess
        env:
          VUE_APP_TITLE: ${{ secrets.VUE_APP_TITLE }}
          VUE_APP_apiKey: ${{ secrets.VUE_APP_apiKey }}
          VUE_APP_authDomain: ${{ secrets.VUE_APP_authDomain }}
          VUE_APP_databaseURL: ${{ secrets.VUE_APP_databaseURL }}
          VUE_APP_projectId: ${{ secrets.VUE_APP_projectId }}
          VUE_APP_storageBucket: ${{ secrets.VUE_APP_storageBucket }}
          VUE_APP_messagingSenderId: ${{ secrets.VUE_APP_messagingSenderId }}
          VUE_APP_appId: ${{ secrets.VUE_APP_appId }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
